<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-0.9.649">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>DC Bike Share Analysis</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
span.underline{text-decoration: underline;}
div.column{display: inline-block; vertical-align: top; width: 50%;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
</style>


<script src="blog_files/libs/clipboard/clipboard.min.js"></script>
<script src="blog_files/libs/quarto-html/quarto.js"></script>
<script src="blog_files/libs/quarto-html/popper.min.js"></script>
<script src="blog_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="blog_files/libs/quarto-html/anchor.min.js"></script>
<link href="blog_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="blog_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="blog_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="blog_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="blog_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">DC Bike Share Analysis</h1>
<p class="subtitle lead">Ben Derenge | August 8, 2022</p>
</div>



<div class="quarto-title-meta">

    
    
  </div>
  

</header>

<p>Washington DC has bike station scattered around the city, allowing anyone find a nearby station, take a bike and ride to another station and drop it off. <em>Capital Bikeshare</em> has publicly available data sets from their website https://ride.capitalbikeshare.com/system-data</p>
<p>There are dozens of data sets on their site, dating b ack to 2011. To begin, I picked a dataset from the first quarter of 2017.</p>
<p>Let’s take a look the data</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>  Duration          Start.date            End.date Start.station.number
1      221 2017-01-01 00:00:41 2017-01-01 00:04:23                31634
2     1676 2017-01-01 00:06:53 2017-01-01 00:34:49                31258
3     1356 2017-01-01 00:07:10 2017-01-01 00:29:47                31289
4     1327 2017-01-01 00:07:22 2017-01-01 00:29:30                31289
5     1636 2017-01-01 00:07:36 2017-01-01 00:34:52                31258
6     1603 2017-01-01 00:08:11 2017-01-01 00:34:55                31258
                                Start.station End.station.number
1                          3rd &amp; Tingey St SE              31208
2                            Lincoln Memorial              31270
3 Henry Bacon Dr &amp; Lincoln Memorial Circle NW              31222
4 Henry Bacon Dr &amp; Lincoln Memorial Circle NW              31222
5                            Lincoln Memorial              31270
6                            Lincoln Memorial              31270
                End.station Bike.number Member.type
1  M St &amp; New Jersey Ave SE      W00869      Member
2             8th &amp; D St NW      W00894      Casual
3 New York Ave &amp; 15th St NW      W21945      Casual
4 New York Ave &amp; 15th St NW      W20012      Casual
5             8th &amp; D St NW      W22786      Casual
6             8th &amp; D St NW      W20890      Casual</code></pre>
</div>
</div>
<p>We see each row is ride. We are given the following info about each ride:</p>
<ul>
<li><p><strong>Duration (minutes)</strong> How many minutes long is the ride</p></li>
<li><p><strong>Start.Date</strong></p></li>
<li><p><strong>End.Date</strong></p></li>
<li><p><strong>Start.station.number</strong> Identifier</p></li>
<li><p><strong>Start.station</strong></p></li>
<li><p><strong>End.station.number</strong> Identifier</p></li>
<li><p><strong>End.station</strong></p></li>
<li><p><strong>Bike.number</strong> bike Identifier</p></li>
<li><p><strong>Member.type</strong> Casual or Member</p>
<p>Looking at the data available, I brainstormed some directions we can go with the data</p></li>
<li><p>What stations are most/least frequently used?</p></li>
<li><p>Time series analysis</p>
<ul>
<li><p>Any daily patterns appear in the data</p></li>
<li><p>Different behaviors in different times of each day</p></li>
<li><p>Seasonal trends</p></li>
</ul></li>
<li><p>“Easy Questions”</p>
<ul>
<li><p>How many bikes are in the data</p></li>
<li><p>How many rides are taken each day</p></li>
<li><p>How many rides per day on average</p></li>
<li><p>What proportion of rides are taken by members</p></li>
</ul></li>
</ul>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Casual Member 
118076 528434 </code></pre>
</div>
<div class="cell-output-display">
<p><img src="blog_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'lubridate'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:base':

    date, intersect, setdiff, union</code></pre>
</div>
</div>
<p>From a simple aggregation, we see in Q1 of 2017 118,076 rides were taken by Casual users, and 528,434 by Members. This is a bit surprising to me</p>
<p>Using the Lubridate package, I converted the date string into a date.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 7104.505</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
</div>
<div class="cell-output-display">
<p><img src="blog_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>This plot shows the distribution of the daily number of ride. It’s a nice looking distribution, with a mean of 7104.5 rides per day.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="blog_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>This time series plot shows a lot of variability. Let’s add a moving average to it.</p>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>Registered S3 method overwritten by 'quantmod':
  method            from
  as.zoo.data.frame zoo </code></pre>
</div>
<div class="cell-output-display">
<p><img src="blog_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Next, I thought to display the rider types on this plot.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>  Member.type      n
1      Casual 118076
2      Member 528434</code></pre>
</div>
<div class="cell-output-display">
<p><img src="blog_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Generally, there are fewer Casuals riding than Member, which is expected as member outnumber casuals 4 to 1. On 3 days, casuals take rides than members. perhaps there was a promotion, or this is due to chance.</p>
<p>Let’s add moving averages to this plot</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="blog_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>This plot look pretty messy, too much going. We could remove actual counts and only see the averages, or simply make the averages easier to see.</p>
<p>Next, I want to make a heatmap to see the busiest day. Using the calendR package,</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 4298</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>~~ Package calendR
Visit https://r-coder.com/ for R tutorials ~~</code></pre>
</div>
<div class="cell-output-display">
<p><img src="blog_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<p><img src="blog_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>                            End.station     n
1       Columbus Circle / Union Station 14660
2  Massachusetts Ave &amp; Dupont Circle NW 10666
3                        15th &amp; P St NW  8879
4             Jefferson Dr &amp; 14th St SW  8411
5                      Lincoln Memorial  7869
6                        14th &amp; V St NW  7289
7                         Thomas Circle  6710
8           New Hampshire Ave &amp; T St NW  6530
9                         5th &amp; K St NW  6154
10                   Jefferson Memorial  5970</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>                                         Start.station     n
1                      Columbus Circle / Union Station 13712
2                 Massachusetts Ave &amp; Dupont Circle NW  9071
3                                       15th &amp; P St NW  8195
4                            Jefferson Dr &amp; 14th St SW  8026
5                                     Lincoln Memorial  7876
6                                        Thomas Circle  7211
7                          New Hampshire Ave &amp; T St NW  6607
8                                       14th &amp; V St NW  6563
9  Eastern Market Metro / Pennsylvania Ave &amp; 7th St SE  5907
10                                       5th &amp; K St NW  5846</code></pre>
</div>
</div>
<section id="most-popular-distination" class="level1">
<h1>Most popular distination</h1>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>  Duration          Start.date            End.date             Start.station
1    23419 2017-01-15 11:23:17 2017-01-15 17:53:36 Jefferson Dr &amp; 14th St SW
2    23389 2017-01-15 11:23:30 2017-01-15 17:53:20 Jefferson Dr &amp; 14th St SW
3    16161 2017-02-24 08:56:43 2017-02-24 13:26:04 Jefferson Dr &amp; 14th St SW
4    16138 2017-02-24 08:57:05 2017-02-24 13:26:03 Jefferson Dr &amp; 14th St SW
5    16058 2017-02-24 08:58:30 2017-02-24 13:26:09 Jefferson Dr &amp; 14th St SW
6    14848 2017-02-20 13:35:00 2017-02-20 17:42:29 Jefferson Dr &amp; 14th St SW
                End.station Member.type
1 Jefferson Dr &amp; 14th St SW      Casual
2 Jefferson Dr &amp; 14th St SW      Casual
3 Jefferson Dr &amp; 14th St SW      Casual
4 Jefferson Dr &amp; 14th St SW      Casual
5 Jefferson Dr &amp; 14th St SW      Casual
6 Jefferson Dr &amp; 14th St SW      Casual</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>  Duration          Start.date            End.date             Start.station
1       62 2017-03-25 14:37:52 2017-03-25 14:38:54 Jefferson Dr &amp; 14th St SW
2       71 2017-01-04 16:44:51 2017-01-04 16:46:02 Jefferson Dr &amp; 14th St SW
3       72 2017-03-23 18:14:02 2017-03-23 18:15:14 Jefferson Dr &amp; 14th St SW
4       74 2017-02-25 15:21:52 2017-02-25 15:23:06 Jefferson Dr &amp; 14th St SW
5       76 2017-01-13 15:08:02 2017-01-13 15:09:19 Jefferson Dr &amp; 14th St SW
6       77 2017-02-07 11:59:16 2017-02-07 12:00:33 Jefferson Dr &amp; 14th St SW
                End.station Member.type
1 Jefferson Dr &amp; 14th St SW      Casual
2 Jefferson Dr &amp; 14th St SW      Member
3 Jefferson Dr &amp; 14th St SW      Casual
4 Jefferson Dr &amp; 14th St SW      Casual
5 Jefferson Dr &amp; 14th St SW      Casual
6 Jefferson Dr &amp; 14th St SW      Casual</code></pre>
</div>
</div>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    setTimeout(function() {
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      let href = ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const cites = ref.parentNode.getAttribute('data-cites').split(' ');
    tippyHover(ref, function() {
      var popup = window.document.createElement('div');
      cites.forEach(function(cite) {
        var citeDiv = window.document.createElement('div');
        citeDiv.classList.add('hanging-indent');
        citeDiv.classList.add('csl-entry');
        var biblioDiv = window.document.getElementById('ref-' + cite);
        if (biblioDiv) {
          citeDiv.innerHTML = biblioDiv.innerHTML;
        }
        popup.appendChild(citeDiv);
      });
      return popup.innerHTML;
    });
  }
});
</script>
</div> <!-- /content -->



</body></html>